### ISSUE TITLE
Showcase usage in README

### ISSUE THREAD

**Issue by elf-pavlik** [o-development/solid-notification-client#3]
@woutslabbinck proposed adding similar documentation to what he did in [solid-notifications-client](https://www.npmjs.com/package/solid-notification-client)

**Comment by woutslabbinck** [comment]
While writing some how to use documentation, I've noticed that the SubscriptionClient might give an ugly error when the channel type is not found.

https://github.com/o-development/solid-notification-client/blob/0d0e1a4832c98cd6fc5cb5d3df3ea0c2f2208119/packages/subscription/src/client.ts#L55

`service` is either a SubscriptionService or null. And when null, this results in following error: 
```
            const response = yield this.authnFetch(service.id, {
                                                           ^

TypeError: Cannot read properties of null (reading 'id')
````

While this can not be resolved per se, wouldn't it be better to throw an Error with a more clear message?

**Comment by elf-pavlik** [comment]
Good catch! Could you create a PR adding an Error? Otherwise, let's create an issue and I can create PR later this week.

**Comment by woutslabbinck** [comment]
I'll create a PR
